# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   username: <%= ENV.fetch("DB_USER", "curumin") %>
#   password: <%= ENV.fetch("DB_PASS", "curumin") %>
#   host: <%= ENV.fetch("DB_HOST", "localhost") %>
#   port: <%= ENV.fetch("DB_PORT", 5432) %>

# development:
#   primary:
#     <<: *default
#     database: <%= ENV.fetch("DB_NAME", "streampix_app") %>_dev
#   cache:
#     <<: *default
#     database: <%= ENV.fetch("DB_NAME", "streampix_app") %>_dev_cache
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *default
#     database: <%= ENV.fetch("DB_NAME", "streampix_app") %>_dev_queue
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *default
#     database: <%= ENV.fetch("DB_NAME", "streampix_app") %>_dev_cable
#     migrations_paths: db/cable_migrate

# test:
#   <<: *default
#   database: <%= ENV.fetch("DB_NAME", "streampix_app") %>_test

# production:
#   primary:
#     <<: *default
#     database: <%= ENV.fetch("DB_NAME", "streampix_app") %>_prod
#   cache:
#     <<: *default
#     database: <%= ENV.fetch("DB_NAME", "streampix_app") %>_prod_cache
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *default
#     database: <%= ENV.fetch("DB_NAME", "streampix_app") %>_prod_queue
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *default
#     database: <%= ENV.fetch("DB_NAME", "streampix_app") %>_prod_cable
#     migrations_paths: db/cable_migrate
# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: storage/development.sqlite3
  cache:
    <<: *default
    database: storage/development_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate


# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: storage/test.sqlite3


# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
production:
  primary:
    <<: *default
    database: storage/production.sqlite3
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate